// Neo4j Cypher Script — Indicador Dependencies
// Ejecución: neo4j-shell < script.cypher

CREATE (:base {id: "cumplimiento_academico", nombre: "Cumplimiento Académico", tipo: "base", in_degree: 2, out_degree: 1})
CREATE (:base {id: "cumplimiento_administrativo", nombre: "Cumplimiento Administrativo", tipo: "base", in_degree: 1, out_degree: 1})
CREATE (:base {id: "cumplimiento_bienestar", nombre: "Cumplimiento Bienestar", tipo: "base", in_degree: 1, out_degree: 1})
CREATE (:compuesto {id: "cmi_estrategico", nombre: "CMI Estratégico", tipo: "compuesto", in_degree: 1, out_degree: 3})
CREATE (:base {id: "ejecucion_presupuestal", nombre: "Ejecución Presupuestal", tipo: "base", in_degree: 1, out_degree: 1})
CREATE (:compuesto {id: "desempeño_general", nombre: "Desempeño General", tipo: "compuesto", in_degree: 0, out_degree: 2})
CREATE (:derivado {id: "tendencia_academica", nombre: "Tendencia Académica", tipo: "derivado", in_degree: 0, out_degree: 1})

MATCH (a { id: "cumplimiento_academico" }), (b { id: "campo_total_cumplido" })
CREATE (a)-[:depende_de]->(b)
MATCH (a { id: "cumplimiento_administrativo" }), (b { id: "campo_total_cumplido" })
CREATE (a)-[:depende_de]->(b)
MATCH (a { id: "cumplimiento_bienestar" }), (b { id: "campo_total_cumplido" })
CREATE (a)-[:depende_de]->(b)
MATCH (a { id: "ejecucion_presupuestal" }), (b { id: "campo_gastos_reales" })
CREATE (a)-[:depende_de]->(b)
MATCH (a { id: "cmi_estrategico" }), (b { id: "cumplimiento_academico" })
CREATE (a)-[:compuesto_de]->(b)
MATCH (a { id: "cmi_estrategico" }), (b { id: "cumplimiento_administrativo" })
CREATE (a)-[:compuesto_de]->(b)
MATCH (a { id: "cmi_estrategico" }), (b { id: "cumplimiento_bienestar" })
CREATE (a)-[:compuesto_de]->(b)
MATCH (a { id: "desempeño_general" }), (b { id: "cmi_estrategico" })
CREATE (a)-[:compuesto_de]->(b)
MATCH (a { id: "desempeño_general" }), (b { id: "ejecucion_presupuestal" })
CREATE (a)-[:compuesto_de]->(b)
MATCH (a { id: "tendencia_academica" }), (b { id: "cumplimiento_academico" })
CREATE (a)-[:transforma]->(b)